<a href="https://colab.research.google.com/github/AnkitaSharma0502/Python_Practice/blob/main/almax_python_level_1_solutions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python Logic Practice**





Welcome — this notebook contains **10 medium-level logic-building problems** with detailed 'thought process' comments in each solution. 😊

**How to use:**
- Read the markdown cell for the problem (Description, Example, Hint).
- Use the "Try it yourself" cell after each solution to experiment with different inputs.
- Run the solution cell below to see the example output and read the inline thought-process comments.



## **Problem 1 — Sum of Pairs Equal to Target**

**Description:**
Given a list of integers and a target integer, return all unique pairs `(a, b)` where `a + b == target`.
Each pair should appear once (order inside pair does not matter).

**Example:**
Input: `nums = [2, 4, 3, 5, 6, -2, 4, 7, 8, 9], target = 7`
Output: `[( -2, 9), (2, 5), (3, 4)]`

**Hint:**
Use a set to track seen numbers and a set to collect result pairs (normalize ordering to avoid duplicates).

**Input/Output example is in the solution cell below.**



In [ ]:
# Try it yourself: modify inputs and run



#### **Solution:**

In [ ]:
def sum_pairs(nums, target):
    # Thought process:
    # 1) We want O(n) time: for each number x, check if target-x was seen before.
    # 2) Use a `seen` set to store numbers we've encountered.
    # 3) Use a `res_set` set to store normalized pairs (min, max) to avoid duplicates.
    # 4) At the end, convert the set to a sorted list for deterministic output.
    seen = set()
    res_set = set()
    for x in nums:
        want = target - x
        if want in seen:
            # normalize pair so (a,b) and (b,a) are considered the same
            a, b = (min(x, want), max(x, want))
            res_set.add((a, b))
        seen.add(x)
    # Convert to sorted list for a stable ordering when returning/printing
    return sorted(list(res_set))

# Example run
print('Example ->', sum_pairs([2,4,3,5,6,-2,4,7,8,9], 7))  # [(-2, 9), (2, 5), (3, 4)]

## **Problem 2 — Character Frequency Pattern Match**

**Description:**

Given two strings, determine if **both have the same frequency pattern** —

that is, if the *counts of characters*, not the characters themselves, occur in the same structure.

**Example:**

```python
Input: s1 = "aabbcc", s2 = "xxyyzz"
Output: True

```

**Explanation:**

Both have the frequency pattern `[2,2,2]`.

Each unique character appears exactly twice.

Another example:

```python
Input: s1 = "aab", s2 = "xyz"
Output: False

```

Reason:

`s1` frequencies → `[2,1]`, `s2` frequencies → `[1,1,1]` → not same.



In [ ]:
# Try it yourself: modify inputs and run


#### **Solution:**

In [ ]:
from collections import Counter

def same_frequency_pattern(s1, s2):
    # Thought process:
    # 1) Count the frequencies of each character in both strings.
    # 2) Extract just the counts (ignore actual characters).
    # 3) Sort and compare frequency patterns.

    freq1 = sorted(Counter(s1).values())
    freq2 = sorted(Counter(s2).values())

    return freq1 == freq2

# Example tests
print(same_frequency_pattern("aabbcc", "xxyyzz"))   # True
print(same_frequency_pattern("aab", "xyz"))         # False
print(same_frequency_pattern("aabbc", "ddeef"))     # True


True
False
True





## **Problem 3 — Word with Maximum Repeating Characters**

**Description:**
Given a sentence (words separated by spaces), return the word that has the largest total count of repeated characters.
Total repeats = sum over characters of (count(ch) - 1) for ch with count>1.

**Example:**
Input: `"test bookkeeper apple"`
Output: `"bookkeeper"`

**Hint:**
For each word compute character frequencies (`collections.Counter`) and the repeat score; choose highest (break ties by first occurrence).

**Input/Output example is in the solution cell below.**



In [ ]:
# Try it yourself: modify inputs and run



#### **Solution:**

In [ ]:
from collections import Counter

def word_with_max_repeats(sentence):
    # Thought process:
    # 1) Split the sentence into words using whitespace.
    # 2) For each word, build a frequency map of characters using Counter.
    # 3) Compute 'repeat score' as sum(count-1 for each char with count>1).
    # 4) Track the word with the highest repeat score; ties resolved by first occurrence.
    best_word = None
    best_score = -1
    for word in sentence.split():
        freq = Counter(word)
        repeats = sum(cnt - 1 for cnt in freq.values() if cnt > 1)
        # If this word has a higher repeat count, update best.
        if repeats > best_score:
            best_score = repeats
            best_word = word
    return best_word

# Example run
print('Example ->', word_with_max_repeats("test bookkeeper appleessllkk"))  # bookkeeper

Example -> appleessllkk


## **Problem 4 — Missing Numbers in a Sequence**

**Description:**
Given a list containing unique numbers from 1..N with some missing, return sorted list of missing numbers.

**Example:**
Input: `nums = [1,2,4,6,7,10], N = 10` → Output: `[3,5,8,9]`

**Hint:**
Use set difference: `set(range(1,N+1)) - set(nums)` and sort the result.

**Input/Output example is in the solution cell below.**




In [ ]:
# Try it yourself: modify inputs and run
#can use set difference
N=10
nums=[1,2,4,6,7,10]
sorted(list(set(range(1,(N+1)))-set(nums)))

[3, 5, 8, 9]

#### **Solution:**

In [ ]:
def missing_numbers(nums, N):
    # Thought process:
    # 1) The expected set of numbers is 1..N. Convert to a set for O(1) membership.
    # 2) Subtract the present numbers set from expected set to get the missing set.
    # 3) Return the sorted list of missing numbers for readability.
    expected = set(range(1, N+1))
    present = set(nums)
    missing = sorted(expected - present)
    return missing

# Example run
print('Example ->', missing_numbers([1,2,4,6,7,10], 10))  # [3,5,8,9]

## **Problem 5 — Sum of Digits Until Single Digit (Digital Root)**

**Description:**

Given a positive integer `n`, repeatedly add its digits until the result becomes a single-digit number, and return that final single digit.

**Example:**

```python
Input: 9875
Output: 2

```

**Explanation:**

```
9 + 8 + 7 + 5 = 29
2 + 9 = 11
1 + 1 = 2

```

Hence, the final single-digit sum is **2**.

**Hint:**

Use a `while` loop to repeatedly compute the sum of digits until `n < 10`.

Alternatively, you can use the **digital root** shortcut formula:

👉 `n = 0 if n == 0 else 9 if n % 9 == 0 else n % 9`

In [2]:
# Try it yourself: modify inputs and run

# n lenge uska sum of digits krenge, jab tak n ka sum single digit nhi ata n ko s se update krte rho


n=9825

while(n>9):
  s=0
  while n>0:
    s=s+n%10
    n=n//10
  n=s

print(s)

6


#### **Solution:**

In [ ]:
def digital_root(n):
    # Thought process:
    # 1) As long as the number has more than one digit,
    #    keep summing its digits.
    # 2) Use //10 and %10 to extract digits, or use str() for simplicity.

    while n >= 10:
        n = sum(int(digit) for digit in str(n))
    return n

# Example test
print(digital_root(9875))  # Output: 2


2


## **Problem 6— Matrix Diagonal Sum**

**Description:**
Given an n x n square matrix, compute the sum of both main diagonals. If n is odd, count the center element only once.

**Example:**
Input:
[[1,2,3],
 [4,5,6],
 [7,8,9]]
Output: 25

**Hint:**
Sum mat[i][i] and mat[i][n-1-i] for i in range(n), subtract center once if n is odd.

**Input/Output example is in the solution cell below.**




In [6]:
# Try it yourself: modify inputs and run
# diagonal element = a[i][i], anti diagonal element = a[i][n-1-i],central element = a[n//2][n//2]
s=0
a= [[1,2,3,4],[4,5,6,7],[7,8,9,1],[1,2,3,4]]
n=len(a)
print(n)
if n%2==0:
  for i in range(0,n):
    s=s+a[i][i]+a[i][n-1-i]
else:
  for i in range(0,n):
    s=s+a[i][i]+a[i][n-1-i]-a[n//2][n//2]
print(s)


4
38


#### **Solution:**

In [8]:
def diagonal_sum(mat):
    # Thought process:
    # 1) Iterate i from 0..n-1, add both mat[i][i] (main diagonal) and mat[i][n-1-i] (anti-diagonal).
    # 2) If n is odd, the center mat[n//2][n//2] has been counted twice; subtract it once.
    n = len(mat)
    if n == 0:
        return 0
    total = 0
    for i in range(n):
        total += mat[i][i]               # main diagonal element
        total += mat[i][n - 1 - i]      # anti-diagonal element mat[1][2]
    if n % 2 == 1:
        # center counted twice — subtract once
        total -= mat[n//2][n//2]
    return total

# Example run
import numpy as np
m = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,1],[1,2,3,4]])
print('Example ->', diagonal_sum(m))  # 25

Example -> 38


In [9]:
for i in m:
  print(i)

[1 2 3 4]
[4 5 6 7]
[7 8 9 1]
[1 2 3 4]


## **Problem 7 — Balanced Number (Symmetry Check)**

**Example 1:**

```python
Input: 1234006
Output: True

```

Explanation:

Left half = 1 + 2 + 3 = 6

Right half = 0 + 0 + 6 = 6 ✅



**Example 2:**

```python
Input: 12321
Output: True

```

Explanation:

Ignore the middle digit (3).

Left = 1 + 2 = 3, Right = 2 + 1 = 3 ✅



**Example 3:**

```python
Input: 123456
Output: False

```

Explanation:

Left = 1 + 2 + 3 = 6

Right = 4 + 5 + 6 = 15 ❌

In [17]:
# Try it yourself: modify inputs and run
def balanced(n):
  s=str(n)
  l=len(s)
  ls = sum(int(s[i]) for i in range(l // 2))
  rs=sum(int(s[j]) for j in range((l//2)+(l % 2),l))
  return ls==rs


balanced(62345416)


False

#### **Solution:**

In [ ]:
def is_balanced_number(num):
    # Thought process:
    # 1) Convert to string for easy indexing.
    # 2) Find midpoint; if odd, skip the middle character.
    # 3) Sum digits on both sides and compare.

    s = str(num)
    n = len(s)
    mid = n // 2

    if n % 2 == 0:
        left = s[:mid]
        right = s[mid:]
    else:
        left = s[:mid]
        right = s[mid+1:]

    left_sum = sum(int(d) for d in left)
    right_sum = sum(int(d) for d in right)

    return left_sum == right_sum

# Example tests
print(is_balanced_number(1234006))  # True
print(is_balanced_number(12321))    # True
print(is_balanced_number(123456))   # False


True
True
False


## **Problem 8 — Sum of the numbers between a to b containing the given digit n**

**Description:**
Given a range a to b and a digit n, find the sum of all the numbers in the range which contains the digit 'n'

**Example:**
adder(1,20,2) returns 34

numbers in the range having the digit 2 : 2,12,20.

Sum=34


In [20]:
# Try it yourself: modify inputs and run
# can convert to string and check for presence of n in that
def addd(a,b,n):
  s=0
  for i in range(a,b+1):
    if str(n) in str(i):
      s=s+i
  return s

addd(1,20,9)

28

#### **Solution:**

In [ ]:

def add(start,end,digit):
  sum=0
  for i in range(start, end+1):
    if str(digit) in str(i):
      sum=sum+i
  return sum

add(1,20,2)

2,12,20



34

## **Problem 9— Alternating Sum Sequence (Odd–Even Adjustment)**

**Description:**

Given a list of integers, compute the alternating sum where you **add numbers at even indices** and **subtract numbers at odd indices**.

Formally, for a list `arr`, return

`arr[0] - arr[1] + arr[2] - arr[3] + …`



**Example:**

```python
Input: [10, 3, 7, 2, 5]
Output: 17

```

**Explanation:**

```
10 - 3 + 7 - 2 + 5 = 17

```



**Example 2:**

```python
Input: [4, 5, 6, 7]
Output: -2

```

Explanation:

`4 - 5 + 6 - 7 = -2`




In [22]:
# Try it yourself: modify inputs and run
def alternate(nums):
  s=0
  for i in range(0,len(nums)):
    if i%2==0:
      s=s+nums[i]
    else:
      s=s-nums[i]
  return s

alternate([4, 5, 6, 7])

-2

#### **Solution:**

In [ ]:
def alternating_sum(nums):
    # Thought process:
    # 1) Initialize total = 0
    # 2) Loop through (index, value) pairs using enumerate().
    # 3) Add value if index is even, subtract if odd.

    total = 0
    for i, val in enumerate(nums):
        if i % 2 == 0:
            total += val
        else:
            total -= val
    return total

# Example runs
print(alternating_sum([10, 3, 7, 2, 5]))  # Output: 17
print(alternating_sum([4, 5, 6, 7]))      # Output: -2


17
-2


## **Problem 10  — Check if Matrix Is a Magic Square**

**Description:**
A square matrix is a magic square if every row, column, and both main diagonals have the same sum. Return True/False.

**Example:**
Input:
[[2,7,6],[9,5,1],[4,3,8]]
Output: True

**Hint:**
Compute the target sum (first row) and verify every row, column, and diagonals equal that.

**Input/Output example is in the solution cell below.**




In [32]:
# Try it yourself: modify inputs and run
def mm(m):
  s = sum(m[0])
  n=len(m)
   # 2. Check each row sum
  for row in m:
      if sum(row) != s:
          return False

    # 3. Check each column sum
  for col in range(n):
      col_sum = sum(m[row][col] for row in range(n))
      if col_sum != s:
          return False

    # 4. Main diagonal
  diag1 = sum(m[i][i] for i in range(n))
  if diag1 != s:
      return False

    # 5. Anti diagonal
  diag2 = sum(m[i][n - i - 1] for i in range(n))
  if diag2 != s:
       return False

  return True



mm([[2,7,6],[9,5,1],[4,3,8]])


True

#### **Solution:**

In [27]:
def is_magic_square(mat):
    # Thought process:
    # 1) Validate matrix is n x n.
    # 2) Compute target sum from first row.
    # 3) Check all row sums, column sums, and both diagonal sums equal target.
    n = len(mat)
    if n == 0:
        return False
    for row in mat:
        if len(row) != n:
            return False
    target = sum(mat[0])
    # check rows
    for i in range(n):
        if sum(mat[i]) != target:
            return False
    # check columns
    for j in range(n):
        if sum(mat[i][j] for i in range(n)) != target:
            return False
    # check diagonals
    if sum(mat[i][i] for i in range(n)) != target:
        return False
    if sum(mat[i][n-1-i] for i in range(n)) != target:
        return False
    return True

# Example run
print('Example ->', is_magic_square([[2,7,6],[9,5,1],[4,3,8]]))  # True

Example -> True
